version: "3.9"

services:
  backend-ci:
    image: node:18
    container_name: backend-ci
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5001:4000"
    command: sh -c "npm install && npm start"

  user-frontend-ci:
    image: node:18
    container_name: user-frontend-ci
    working_dir: /app
    volumes:
      - ./user-frontend:/app
    ports:
      - "3005:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend-ci

  admin-frontend-ci:
    image: node:18
    container_name: admin-frontend-ci
    working_dir: /app
    volumes:
      - ./admin-frontend:/app
    ports:
      - "3006:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend-ci
